# [time]
# disabled = false
# format = '🕙[\[ $time \]]($style) '
# time_format = "%T"

[directory]
truncation_length = 3
***REMOVED***sh_style_pwd_dir_length = 1

[gcloud]
disabled = true

[aws]
disabled = true
